import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const cameras = [
  { title: "Venice Beach Boardwalk",     slug: "venice-beach",          lat: 33.9850,   lng: -118.4695,  city: "Los Angeles",      country: "USA",          category: "BEACH", timezone: "America/Los_Angeles",  streamUrl: "https://www.youtube.com/watch?v=EO_1LWqsCNE",  description: "Eagle-eye view of Venice Beach from the Venice V Hotel. Watch skaters, surfers, and the legendary boardwalk live." },
  { title: "Surfline Global Surf Cams",  slug: "surfline-global",       lat: 21.2766,   lng: -157.8275,  city: "Worldwide",         country: "Global",        category: "BEACH", timezone: "Pacific/Honolulu",     streamUrl: "https://www.youtube.com/watch?v=hm9iAviOZ20",  description: "Surfline TV rotates through the world's best surf spots 24/7. Pipeline, Malibu, Bondi." },
  { title: "Outer Banks Beach",          slug: "outer-banks",           lat: 36.0895,   lng: -75.7055,   city: "Kitty Hawk",       country: "USA",          category: "BEACH", timezone: "America/New_York",     streamUrl: "https://www.youtube.com/watch?v=WEhuDqlxHmM",  description: "Live 24/7 beach cam from Kitty Hawk, NC. Real-time ocean views, weather, and Atlantic waves." },
  { title: "Koh Samui Crystal Bay",      slug: "koh-samui-beach",       lat: 9.4680,    lng: 100.0580,   city: "Koh Samui",        country: "Thailand",      category: "BEACH", timezone: "Asia/Bangkok",          streamUrl: "https://www.youtube.com/watch?v=kkVrj2cr9Ko",  description: "1080p HD beach cam at Crystal Bay Yacht Club. Turquoise Gulf of Thailand waters and swaying palms." },
  { title: "Miura Beach Japan",          slug: "miura-beach-japan",     lat: 35.1917,   lng: 139.6503,   city: "Miura",            country: "Japan",         category: "BEACH", timezone: "Asia/Tokyo",            streamUrl: "https://www.youtube.com/watch?v=PrGQsGUAnk0",  description: "Peaceful 24/7 view of Miura Beach near Tokyo. Ocean waves and Japanese coastline serenity." },
  { title: "Maldives InterContinental",   slug: "maldives-beach",        lat: 4.2240,    lng: 73.5018,    city: "Raa Atoll",        country: "Maldives",      category: "BEACH", timezone: "Indian/Maldives",       streamUrl: "https://www.youtube.com/watch?v=_BMi3usEwi8",  description: "4K tropical beach at the InterContinental Maldives. Sunset views, crystal water, pure paradise." },
  { title: "Oceanside Rooftop Bar",      slug: "oceanside-san-diego",   lat: 33.1959,   lng: -117.3795,  city: "Oceanside",        country: "USA",          category: "BEACH", timezone: "America/Los_Angeles",  streamUrl: "https://www.youtube.com/watch?v=cvP_F-c2Upw",  description: "Sixth-floor rooftop from Mission Pacific Beach Resort. Pacific Ocean panorama over San Diego coast." },
  { title: "Tahiti & Hawaii Big Waves",  slug: "tahiti-hawaii-waves",   lat: -17.6509,  lng: -149.4260,  city: "Tahiti",           country: "French Polynesia", category: "BEACH", timezone: "Pacific/Tahiti",        streamUrl: "https://www.youtube.com/watch?v=6N8jzXAstuk",  description: "4K 24/7 massive waves from Tahiti and Hawaii. Teahupo'o barrels and North Shore power." },
  { title: "Rio de Janeiro Boat View",   slug: "rio-boat-view",         lat: -22.9711,  lng: -43.1823,   city: "Rio de Janeiro",   country: "Brazil",        category: "BEACH", timezone: "America/Sao_Paulo",     streamUrl: "https://www.youtube.com/watch?v=VnsRQvfv_g4",  description: "24/7 live from a boat in Rio. Coastline views, Sugarloaf Mountain, Copacabana vibes." },
  { title: "Underwater Reef Cam",        slug: "underwater-reef",       lat: 16.4000,   lng: -86.4000,   city: "Utopia Village",   country: "Honduras",      category: "BEACH", timezone: "America/Tegucigalpa",   streamUrl: "https://www.youtube.com/watch?v=jzx_n25g3kA",  description: "Underwater reef camera by EXPLORE.org. Tropical fish, coral, and marine life at 20ft depth." },
  { title: "Shinjuku Kabukicho Tokyo",   slug: "shinjuku-kabukicho",    lat: 35.6938,   lng: 139.7036,   city: "Tokyo",            country: "Japan",         category: "CITY",  timezone: "Asia/Tokyo",            streamUrl: "https://www.youtube.com/watch?v=DjdUEyjx8GM",  description: "24-hour live camera at Kabukicho Ichibangai, Shinjuku. Neon lights and Tokyo nightlife." },
  { title: "Tokyo Skyline View",         slug: "tokyo-skyline",         lat: 35.6762,   lng: 139.7607,   city: "Tokyo",            country: "Japan",         category: "CITY",  timezone: "Asia/Tokyo",            streamUrl: "https://www.youtube.com/watch?v=_k-5U7IeK8g",  description: "Live Tokyo cityscape with lofi & soft jazz. Tokyo Tower and skyline views." },
  { title: "Taiwan Taoyuan Airport",     slug: "taoyuan-airport",       lat: 25.0797,   lng: 121.2336,   city: "Taoyuan",          country: "Taiwan",        category: "CITY",  timezone: "Asia/Taipei",           streamUrl: "https://www.youtube.com/watch?v=91PfFoqvuUk",  description: "4K live cam at Taiwan's largest international airport. Planes take off against mountain backdrop." },
  { title: "Koh Samui Street Food Bar",  slug: "koh-samui-bar",         lat: 9.5285,    lng: 100.0584,   city: "Koh Samui",        country: "Thailand",      category: "CITY",  timezone: "Asia/Bangkok",          streamUrl: "https://www.youtube.com/watch?v=VR-x3HdhKLQ",  description: "4K live from Bondi Aussie Bar & Grill on Chaweng Beach Road. Street life and tropical island vibes." },
  { title: "Big Bear Bald Eagle Nest",   slug: "bald-eagle-nest",       lat: 34.2439,   lng: -116.9120,  city: "Big Bear Lake",    country: "USA",          category: "NATURE", timezone: "America/Los_Angeles",  streamUrl: "https://www.youtube.com/watch?v=B4-L2nfGcuE",  description: "Live bald eagle nest cam. Watch nesting eagles raise their young in the San Bernardino mountains." },
  { title: "Namib Desert Live",          slug: "namib-desert",          lat: -24.5500,  lng: 15.8000,    city: "Namib Desert",     country: "Namibia",       category: "NATURE", timezone: "Africa/Windhoek",        streamUrl: "https://www.youtube.com/watch?v=ydYDqZQpim8",  description: "Endless red dunes, open plains, and untamed African wildlife roaming free in the legendary Namib Desert." },
  { title: "Danish Forest Wildlife",     slug: "danish-forest",         lat: 56.2639,   lng: 9.5018,     city: "Silkeborg",        country: "Denmark",       category: "NATURE", timezone: "Europe/Copenhagen",      streamUrl: "https://www.youtube.com/watch?v=F0GOOP82094",  description: "Peaceful 24/7 nature cam in a Danish forest. Deer, birds, foxes pass through the clearing." },
  { title: "Austria Alpine Panorama",    slug: "austria-alps",          lat: 47.2692,   lng: 11.4041,    city: "Innsbruck",        country: "Austria",       category: "NATURE", timezone: "Europe/Vienna",           streamUrl: "https://www.youtube.com/watch?v=NIuO6hrFTrg",  description: "24/7 weather panorama across Austria. Alpine peaks from Innsbruck to Vienna." },
  { title: "Red Squirrel Studios",       slug: "red-squirrel-birds",    lat: 52.5000,   lng: -1.9000,    city: "Birmingham",       country: "UK",            category: "NATURE", timezone: "Europe/London",          streamUrl: "https://www.youtube.com/watch?v=UEyEs8AE1ss",  description: "24/7 nature cam — birds and red squirrels at a garden feeding station. Pure nature therapy." },
  { title: "CritterVision Wildlife Cam", slug: "crittervision",         lat: 35.5000,   lng: -82.5000,   city: "Appalachia",       country: "USA",          category: "NATURE", timezone: "America/New_York",     streamUrl: "https://www.youtube.com/watch?v=HlJ4aRtYhoo",  description: "24/7 wildlife cam from a rural property. Raccoons, deer, opossums, birds at all hours." },
  { title: "SpaceX Starbase 24/7",       slug: "spacex-starbase",       lat: 25.9902,   lng: -97.1570,   city: "Boca Chica",       country: "USA",          category: "EVENT", timezone: "America/Chicago",       streamUrl: "https://www.youtube.com/watch?v=mhJRzQsLZGg",  description: "24/7 live stream of SpaceX's Starbase facility. Watch Starship development and launches from Boca Chica, Texas." },
  { title: "ISS Earth View 4K",          slug: "iss-earth-view",        lat: 0,         lng: 0,          city: "Low Earth Orbit",  country: "Space",         category: "EVENT", timezone: "UTC",                    streamUrl: "https://www.youtube.com/watch?v=fO9e9jnhYK8",  description: "Live 4K video of Earth from Sen's cameras on the International Space Station. Watch our planet from 400km above." },
  { title: "ISS Live Stream",            slug: "iss-live",              lat: 0,         lng: 0,          city: "Low Earth Orbit",  country: "Space",         category: "EVENT", timezone: "UTC",                    streamUrl: "https://www.youtube.com/watch?v=0FBiyFpV__g",  description: "24/7 live from the International Space Station. Orbit Earth and see continents pass below." },
  { title: "Jennette's Pier Beach",      slug: "jennettes-pier",        lat: 35.9102,   lng: -75.5950,   city: "Nags Head",        country: "USA",          category: "BEACH", timezone: "America/New_York",     streamUrl: "https://5a5f765a4fcc2.streamlock.net:1936/live/nh4.stream/playlist.m3u8", description: "Direct HLS stream from Jennette's Pier in North Carolina. Atlantic beach waves and coastal weather live." },
  { title: "San Diego Zoo Platypus Cam", slug: "platypus-cam",          lat: 32.7353,   lng: -117.1490,  city: "San Diego",        country: "USA",          category: "NATURE", timezone: "America/Los_Angeles",  streamUrl: "https://zssd-platypus.hls.camzonecdn.com/CamzoneStreams/zssd-platypus/Playlist.m3u8", description: "Live platypus cam from the San Diego Zoo. Watch these unique Australian monotremes swim and play." },
  { title: "Bay Bridge Traffic Cam",     slug: "bay-bridge-traffic",    lat: 37.7899,   lng: -122.3878,  city: "San Francisco",    country: "USA",          category: "CITY",  timezone: "America/Los_Angeles",  streamUrl: "https://kntvlive-f.akamaihd.net/i/kntvb1_1@15530/master.m3u8", description: "Live traffic cam on the San Francisco Bay Bridge. Watch the flow of the city across the water." },
]

async function main() {
  await prisma.favorite.deleteMany()
  await prisma.cameraSource.deleteMany()
  console.log(`Seeding ${cameras.length} real live cameras...`)
  for (const cam of cameras) {
    await prisma.cameraSource.create({ data: cam })
  }
  console.log(`Seeded ${cameras.length} cameras (all verified LIVE on YouTube 2026-06-23)`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
